wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    code_path: code/base.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1666244221.760114
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.8.13
      5: 0.13.4
      8:
      - 5
capture_video:
  desc: null
  value: false
cuda:
  desc: null
  value: false
exp_name:
  desc: null
  value: base
gym_id:
  desc: null
  value: CartPole-v1
learning_rate:
  desc: null
  value: 0.00025
mps:
  desc: null
  value: true
seed:
  desc: null
  value: 1
torch_deterministic:
  desc: null
  value: true
total_timesteps:
  desc: null
  value: 25000
track:
  desc: null
  value: true
wandb_entity:
  desc: null
  value: null
wandb_project_name:
  desc: null
  value: ppo-implementation-details
