wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    code_path: code/ant_ppo.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.0
    start_time: 1669076560.993449
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.8.0
      5: 0.13.5
      8:
      - 5
anneal_lr:
  desc: null
  value: true
batch_size:
  desc: null
  value: 2048
capture_video:
  desc: null
  value: true
clip_coef:
  desc: null
  value: 0.2
clip_vloss:
  desc: null
  value: true
cuda:
  desc: null
  value: true
ent_coef:
  desc: null
  value: 0.0
exp_name:
  desc: null
  value: ant_ppo
gae:
  desc: null
  value: true
gae_lambda:
  desc: null
  value: 0.95
gamma:
  desc: null
  value: 0.99
gym_id:
  desc: null
  value: Ant-v3
learning_rate:
  desc: null
  value: 0.0003
max_grad_norm:
  desc: null
  value: 0.5
minibatch_size:
  desc: null
  value: 64
norm_adv:
  desc: null
  value: true
num_envs:
  desc: null
  value: 1
num_minibatches:
  desc: null
  value: 32
num_steps:
  desc: null
  value: 2048
seed:
  desc: null
  value: 42
target_kl:
  desc: null
  value: null
torch_deterministic:
  desc: null
  value: true
total_timesteps:
  desc: null
  value: 2000000
track:
  desc: null
  value: true
update_epochs:
  desc: null
  value: 10
vf_coef:
  desc: null
  value: 0.5
wandb_entity:
  desc: null
  value: null
wandb_project_name:
  desc: null
  value: ppo-implementation-details
